### ISSUE TITLE
[Issue] Tiles don't match the ones used in the TMX file.

### ISSUE THREAD

**Issue by thetestgame** [janEntikan/tmx2bam#1]
A quick comparison of the issue with a bucket fill TMX file. It appears as if tmx2bam is choosing a different tile then the one required for the slot. The version of Tiled being used is version 1.4.2. I've included the TMX file used to demo this as well as the required tsx and png file.

![Gyazo](https://i.gyazo.com/f5e3045bb0adba53b669ebf2b9bc651c.png)

[world.zip](https://github.com/janEntikan/tmx2bam/files/5470296/world.zip)

**Comment by janEntikan** [comment]
Fixed and thanks so much :)
